<?php 
declare(strict_types=1);
# Generated by the Minichan compiler. DO NOT EDIT!
# source: proto/chatapp.proto

namespace PHP\ChatApp;


interface ChatAppServiceInterface extends \Minichan\Grpc\ServiceInterface
{
    public const NAME = "/PHP.ChatApp.ChatAppService";

    /**
    * @param \Minichan\Grpc\ContextInterface $ctx
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function RegisterUser(\Minichan\Grpc\ContextInterface $ctx, Users $request): Response;

    /**
    * @param \Minichan\Grpc\ContextInterface $ctx
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function Login(\Minichan\Grpc\ContextInterface $ctx, Users $request): Response;

    /**
    * @param \Minichan\Grpc\ContextInterface $ctx
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function Logout(\Minichan\Grpc\ContextInterface $ctx, Users $request): Response;

    /**
    * @param \Minichan\Grpc\ContextInterface $ctx
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function GetUsersList(\Minichan\Grpc\ContextInterface $ctx, Users $request): Response;

    /**
    * @param \Minichan\Grpc\ContextInterface $ctx
    * @param Users $request
    * @return UserResponse
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function GetCurrentUser(\Minichan\Grpc\ContextInterface $ctx, Users $request): UserResponse;

    /**
    * @param \Minichan\Grpc\ContextInterface $ctx
    * @param Message $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function InsertMessage(\Minichan\Grpc\ContextInterface $ctx, Message $request): Response;

    /**
    * @param \Minichan\Grpc\ContextInterface $ctx
    * @param Message $request
    * @return MessagesResponse
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function GetMessage(\Minichan\Grpc\ContextInterface $ctx, Message $request): MessagesResponse;

    /**
    * @param \Minichan\Grpc\ContextInterface $ctx
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function Search(\Minichan\Grpc\ContextInterface $ctx, Users $request): Response;
}
