<?php declare(strict_types=1);
# Generated by the Minichan compiler. DO NOT EDIT!
# source: proto/chatapp.proto

namespace PHP\ChatApp;


class ChatAppServiceClient extends \Minichan\Grpc\BaseStub
{


	/**
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function RegisterUser(Users $request, $metadata = []): Response {
    	return $this->_serverStreamRequest('/PHP.ChatApp.ChatAppService/RegisterUser',
        $request,
        ['\PHP\ChatApp\Response', 'decode'],
        $metadata); 
    }

	public function getNext(): object {
	    return $this->_getData();
	}



	/**
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function Login(Users $request, $metadata = []): Response {
    	return $this->_serverStreamRequest('/PHP.ChatApp.ChatAppService/Login',
        $request,
        ['\PHP\ChatApp\Response', 'decode'],
        $metadata); 
    }



	/**
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function Logout(Users $request, $metadata = []): Response {
    	return $this->_serverStreamRequest('/PHP.ChatApp.ChatAppService/Logout',
        $request,
        ['\PHP\ChatApp\Response', 'decode'],
        $metadata); 
    }



	/**
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function GetUsersList(Users $request, $metadata = []): Response {
    	return $this->_serverStreamRequest('/PHP.ChatApp.ChatAppService/GetUsersList',
        $request,
        ['\PHP\ChatApp\Response', 'decode'],
        $metadata); 
    }



	/**
    * @param Users $request
    * @return UserResponse
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function GetCurrentUser(Users $request, $metadata = []): UserResponse {
    	return $this->_serverStreamRequest('/PHP.ChatApp.ChatAppService/GetCurrentUser',
        $request,
        ['\PHP\ChatApp\UserResponse', 'decode'],
        $metadata); 
    }



	/**
    * @param Message $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function InsertMessage(Message $request, $metadata = []): Response {
    	return $this->_serverStreamRequest('/PHP.ChatApp.ChatAppService/InsertMessage',
        $request,
        ['\PHP\ChatApp\Response', 'decode'],
        $metadata); 
    }



	/**
    * @param Message $request
    * @return MessagesResponse
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function GetMessage(Message $request, $metadata = []): MessagesResponse {
    	return $this->_serverStreamRequest('/PHP.ChatApp.ChatAppService/GetMessage',
        $request,
        ['\PHP\ChatApp\MessagesResponse', 'decode'],
        $metadata); 
    }



	/**
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function Search(Users $request, $metadata = []): Response {
    	return $this->_serverStreamRequest('/PHP.ChatApp.ChatAppService/Search',
        $request,
        ['\PHP\ChatApp\Response', 'decode'],
        $metadata); 
    }
}
