<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/chatapp.proto

namespace PHP\ChatApp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PHP.ChatApp.MessagesResponse</code>
 */
class MessagesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .PHP.ChatApp.Message messages = 1;</code>
     */
    private $messages;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \PHP\ChatApp\Message[]|\Google\Protobuf\Internal\RepeatedField $messages
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Chatapp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .PHP.ChatApp.Message messages = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMessages()
    {
        return $this->messages;
    }

    /**
     * Generated from protobuf field <code>repeated .PHP.ChatApp.Message messages = 1;</code>
     * @param \PHP\ChatApp\Message[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMessages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PHP\ChatApp\Message::class);
        $this->messages = $arr;

        return $this;
    }

}

