<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/chatapp.proto

namespace PHP\ChatApp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PHP.ChatApp.Message</code>
 */
class Message extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 msg_id = 1;</code>
     */
    protected $msg_id = 0;
    /**
     * Generated from protobuf field <code>int32 incomming_msg_id = 2;</code>
     */
    protected $incomming_msg_id = 0;
    /**
     * Generated from protobuf field <code>int32 outgoing_msg_id = 3;</code>
     */
    protected $outgoing_msg_id = 0;
    /**
     * Generated from protobuf field <code>string msg = 4;</code>
     */
    protected $msg = '';
    /**
     * Generated from protobuf field <code>string img = 5;</code>
     */
    protected $img = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $msg_id
     *     @type int $incomming_msg_id
     *     @type int $outgoing_msg_id
     *     @type string $msg
     *     @type string $img
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Chatapp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 msg_id = 1;</code>
     * @return int
     */
    public function getMsgId()
    {
        return $this->msg_id;
    }

    /**
     * Generated from protobuf field <code>int32 msg_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkInt32($var);
        $this->msg_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 incomming_msg_id = 2;</code>
     * @return int
     */
    public function getIncommingMsgId()
    {
        return $this->incomming_msg_id;
    }

    /**
     * Generated from protobuf field <code>int32 incomming_msg_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIncommingMsgId($var)
    {
        GPBUtil::checkInt32($var);
        $this->incomming_msg_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 outgoing_msg_id = 3;</code>
     * @return int
     */
    public function getOutgoingMsgId()
    {
        return $this->outgoing_msg_id;
    }

    /**
     * Generated from protobuf field <code>int32 outgoing_msg_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOutgoingMsgId($var)
    {
        GPBUtil::checkInt32($var);
        $this->outgoing_msg_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg = 4;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string img = 5;</code>
     * @return string
     */
    public function getImg()
    {
        return $this->img;
    }

    /**
     * Generated from protobuf field <code>string img = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->img = $var;

        return $this;
    }

}

