<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/chatapp.proto

namespace PHP\ChatApp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PHP.ChatApp.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool successOrError = 1;</code>
     */
    protected $successOrError = false;
    /**
     * Generated from protobuf field <code>.PHP.ChatApp.Users user = 2;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>repeated .PHP.ChatApp.Users users = 3;</code>
     */
    private $users;
    /**
     * Generated from protobuf field <code>.PHP.ChatApp.Message message = 4;</code>
     */
    protected $message = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $successOrError
     *     @type \PHP\ChatApp\Users $user
     *     @type \PHP\ChatApp\Users[]|\Google\Protobuf\Internal\RepeatedField $users
     *     @type \PHP\ChatApp\Message $message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Chatapp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool successOrError = 1;</code>
     * @return bool
     */
    public function getSuccessOrError()
    {
        return $this->successOrError;
    }

    /**
     * Generated from protobuf field <code>bool successOrError = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccessOrError($var)
    {
        GPBUtil::checkBool($var);
        $this->successOrError = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.PHP.ChatApp.Users user = 2;</code>
     * @return \PHP\ChatApp\Users
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.PHP.ChatApp.Users user = 2;</code>
     * @param \PHP\ChatApp\Users $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \PHP\ChatApp\Users::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .PHP.ChatApp.Users users = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * Generated from protobuf field <code>repeated .PHP.ChatApp.Users users = 3;</code>
     * @param \PHP\ChatApp\Users[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PHP\ChatApp\Users::class);
        $this->users = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.PHP.ChatApp.Message message = 4;</code>
     * @return \PHP\ChatApp\Message
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>.PHP.ChatApp.Message message = 4;</code>
     * @param \PHP\ChatApp\Message $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkMessage($var, \PHP\ChatApp\Message::class);
        $this->message = $var;

        return $this;
    }

}

