<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/chatapp.proto

namespace PHP\ChatApp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PHP.ChatApp.UserResponse</code>
 */
class UserResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.PHP.ChatApp.Users user = 1;</code>
     */
    protected $user = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \PHP\ChatApp\Users $user
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Chatapp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.PHP.ChatApp.Users user = 1;</code>
     * @return \PHP\ChatApp\Users
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.PHP.ChatApp.Users user = 1;</code>
     * @param \PHP\ChatApp\Users $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \PHP\ChatApp\Users::class);
        $this->user = $var;

        return $this;
    }

}

